### ISSUE TITLE
Roadmap & Known Issues

### ISSUE THREAD

**Issue by haren724** [haren724/open-wallpaper-engine-mac#12]
This issue was drafted for marking the known issue which includes in-progress or waiting to be solved issues, and also for everyone who is currently testing for this app to get the latest progress.

### UI Components
- [ ] Many components are in developing. It's normal to discover that clicking some of them like workshop will have no response.
#### GifImage View
- [x] Have problems in auto scaling
#### FilterResults View
- [ ] Filters now can't work with ContentView because they two aren't connected currently

### Utility
- [ ] Multiple Screens now can't be detected and modified.
- [ ] Scene Wallpaper can't be imported (pls don't try to import them)
- [x] Can't customize the wallpaper's playback settings currently (but very soon!)
- [ ] Can only import wallpapers from menu bat - File - Import. It doesn't mean you can't even import wallpapers by dragging them directly into application container directory, but not encouraged to do that.

## Small Tips
- To jump to wallpaper folder, right click in main window's Grid View and select 'Open Wallpapers Folder in Finder'
