### ISSUE TITLE
Roadmap New (for TestFlight)

### ISSUE THREAD

**Issue by haren724** [haren724/open-wallpaper-engine-mac#22]
## 0.6.0
- [ ] Multi-display management
- [ ] 

## 0.5.1
- [ ] Playback settings in SettingsView now take effect

## 0.5.0
- [ ] Interactive web wallpaper

## 0.4.1
- [ ] Import .mp4 files directly by dragging into main window
- [ ] ...

**Comment by lxhj** [comment]
支持！

**Comment by gowellwei** [comment]
干干干！！！
